console.log('🔍 To get your access token for debugging:');
console.log('');
console.log('1. Open your browser console (F12)');
console.log('2. Run this command:');
console.log('   localStorage.getItem("accessToken")');
console.log('');
console.log('3. Copy the token and run:');
console.log('   $env:ACCESS_TOKEN="YOUR_TOKEN_HERE"');
console.log('   node debug-instructor-auth.js');
console.log('');
console.log('Or alternatively, check the Network tab in DevTools when you make the delete request to see the exact error response.'); 