// ===============================================
// Centralized Error Codes
// ===============================================

export const ERROR_CODES = {
  // Validation Errors (400x)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_PHONE: 'INVALID_PHONE',
  INVALID_DATE: 'INVALID_DATE',
  
  // Authentication Errors (401x)
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_CREDENTIALS_INVALID: 'AUTH_CREDENTIALS_INVALID',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_LOGOUT_REQUIRED: 'AUTH_LOGOUT_REQUIRED',
  
  // Authorization Errors (403x)
  ACCESS_FORBIDDEN: 'ACCESS_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  ROLE_REQUIRED: 'ROLE_REQUIRED',
  ORGANIZATION_ACCESS_DENIED: 'ORGANIZATION_ACCESS_DENIED',
  
  // Resource Errors (404x)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  ENDPOINT_NOT_FOUND: 'ENDPOINT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  INSTRUCTOR_NOT_FOUND: 'INSTRUCTOR_NOT_FOUND',
  
  // Business Logic Errors (409x)
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  SCHEDULE_CONFLICT: 'SCHEDULE_CONFLICT',
  COURSE_ALREADY_CONFIRMED: 'COURSE_ALREADY_CONFIRMED',
  INSTRUCTOR_UNAVAILABLE: 'INSTRUCTOR_UNAVAILABLE',
  
  // Rate Limiting (429x)
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // External Service Errors (502x)
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EXTERNAL_SERVICE_TIMEOUT: 'EXTERNAL_SERVICE_TIMEOUT',
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EMAIL_SERVICE_ERROR: 'EMAIL_SERVICE_ERROR',
  
  // Database Errors (503x)
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  
  // System Errors (500x)
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  CONFIGURATION_ERROR: 'CONFIGURATION_ERROR',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  
  // Network Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  CONNECTION_TIMEOUT: 'CONNECTION_TIMEOUT',
  CONNECTION_REFUSED: 'CONNECTION_REFUSED',
  
  // File/Upload Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  
  // Payment/Billing Errors
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_PROCESSING_ERROR: 'PAYMENT_PROCESSING_ERROR',
  INVOICE_GENERATION_ERROR: 'INVOICE_GENERATION_ERROR',
  BILLING_ERROR: 'BILLING_ERROR',
} as const;

// Error code to HTTP status mapping
export const ERROR_CODE_TO_STATUS: Record<string, number> = {
  // 400 - Bad Request
  [ERROR_CODES.VALIDATION_ERROR]: 400,
  [ERROR_CODES.INVALID_INPUT]: 400,
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,
  [ERROR_CODES.INVALID_FORMAT]: 400,
  [ERROR_CODES.INVALID_EMAIL]: 400,
  [ERROR_CODES.INVALID_PASSWORD]: 400,
  [ERROR_CODES.INVALID_PHONE]: 400,
  [ERROR_CODES.INVALID_DATE]: 400,
  [ERROR_CODES.FILE_TOO_LARGE]: 400,
  [ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: 400,
  
  // 401 - Unauthorized
  [ERROR_CODES.AUTH_TOKEN_MISSING]: 401,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 401,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.AUTH_CREDENTIALS_INVALID]: 401,
  [ERROR_CODES.AUTH_SESSION_EXPIRED]: 401,
  [ERROR_CODES.AUTH_LOGOUT_REQUIRED]: 401,
  
  // 403 - Forbidden
  [ERROR_CODES.ACCESS_FORBIDDEN]: 403,
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
  [ERROR_CODES.RESOURCE_ACCESS_DENIED]: 403,
  [ERROR_CODES.ROLE_REQUIRED]: 403,
  [ERROR_CODES.ORGANIZATION_ACCESS_DENIED]: 403,
  
  // 404 - Not Found
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 404,
  [ERROR_CODES.ENDPOINT_NOT_FOUND]: 404,
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.COURSE_NOT_FOUND]: 404,
  [ERROR_CODES.ORGANIZATION_NOT_FOUND]: 404,
  [ERROR_CODES.INSTRUCTOR_NOT_FOUND]: 404,
  
  // 409 - Conflict
  [ERROR_CODES.RESOURCE_CONFLICT]: 409,
  [ERROR_CODES.BUSINESS_RULE_VIOLATION]: 409,
  [ERROR_CODES.DUPLICATE_RESOURCE]: 409,
  [ERROR_CODES.DUPLICATE_EMAIL]: 409,
  [ERROR_CODES.SCHEDULE_CONFLICT]: 409,
  [ERROR_CODES.COURSE_ALREADY_CONFIRMED]: 409,
  [ERROR_CODES.INSTRUCTOR_UNAVAILABLE]: 409,
  
  // 429 - Too Many Requests
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 429,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  
  // 500 - Internal Server Error
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODES.UNEXPECTED_ERROR]: 500,
  [ERROR_CODES.CONFIGURATION_ERROR]: 500,
  [ERROR_CODES.DATABASE_CONNECTION_ERROR]: 500,
  [ERROR_CODES.DATABASE_QUERY_ERROR]: 500,
  [ERROR_CODES.DATABASE_CONSTRAINT_VIOLATION]: 500,
  [ERROR_CODES.DATABASE_TIMEOUT]: 500,
  [ERROR_CODES.UPLOAD_FAILED]: 500,
  [ERROR_CODES.PAYMENT_PROCESSING_ERROR]: 500,
  [ERROR_CODES.INVOICE_GENERATION_ERROR]: 500,
  [ERROR_CODES.BILLING_ERROR]: 500,
  
  // 502 - Bad Gateway
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 502,
  [ERROR_CODES.EMAIL_SERVICE_ERROR]: 502,
  
  // 503 - Service Unavailable
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
  [ERROR_CODES.EXTERNAL_SERVICE_UNAVAILABLE]: 503,
  
  // 504 - Gateway Timeout
  [ERROR_CODES.EXTERNAL_SERVICE_TIMEOUT]: 504,
  [ERROR_CODES.CONNECTION_TIMEOUT]: 504,
  
  // Network errors (treated as 500)
  [ERROR_CODES.NETWORK_ERROR]: 500,
  [ERROR_CODES.CONNECTION_REFUSED]: 500,
  [ERROR_CODES.PAYMENT_FAILED]: 402,
};

// User-friendly error messages
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.VALIDATION_ERROR]: 'Please check your input and try again',
  [ERROR_CODES.INVALID_INPUT]: 'The provided information is invalid',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Please fill in all required fields',
  [ERROR_CODES.INVALID_EMAIL]: 'Please enter a valid email address',
  [ERROR_CODES.INVALID_PASSWORD]: 'Password does not meet requirements',
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 'Your session has expired. Please log in again',
  [ERROR_CODES.AUTH_CREDENTIALS_INVALID]: 'Invalid username or password',
  [ERROR_CODES.ACCESS_FORBIDDEN]: 'You do not have permission to access this resource',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'The requested resource was not found',
  [ERROR_CODES.NETWORK_ERROR]: 'Network connection error. Please check your internet connection',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 'An unexpected error occurred. Please try again later',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service is temporarily unavailable. Please try again later',
  [ERROR_CODES.DUPLICATE_EMAIL]: 'This email address is already registered',
  [ERROR_CODES.SCHEDULE_CONFLICT]: 'There is a scheduling conflict with the selected time',
  [ERROR_CODES.INSTRUCTOR_UNAVAILABLE]: 'The selected instructor is not available at this time',
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Too many requests. Please wait a moment and try again',
  [ERROR_CODES.FILE_TOO_LARGE]: 'File size is too large. Please select a smaller file',
  [ERROR_CODES.FILE_TYPE_NOT_ALLOWED]: 'File type is not allowed. Please select a different file',
  [ERROR_CODES.PAYMENT_FAILED]: 'Payment processing failed. Please check your payment information',
};

export type ErrorCode = keyof typeof ERROR_CODES; 